### ISSUE TITLE
phyint management

### ISSUE THREAD

**Issue by mweinelt** [troglobit/pim6sd#4]
pim6sd, as pimd and probably other tools, tries to listen on all interfaces it sees by default. I would kindly ask you to revisit that default and only listen to configured interfaces, so I can safely and explicitly decide where to support multicast. This is a default I greatly appreciate in other routing daemons, like bird or babeld.

From my POV It makes little sense to listen on interfaces that are neither access links to client devices nor backbone links where multicast is being forwarded in between.

I currently need to `phyint [...] disable` 15 interfaces because they're one of
- lacp hardlinks
- bridge ports (interfaces enslaved to a bridge)
- 802.1q trunks
- management networks
- loopback interfaces

The way it is now If another interface popped up it would be inadvertently used by pim6sd, whether I liked that or not.

Thanks for your work!

**Comment by troglobit** [comment]
Good point!  However, as I mentioned previously, I'd like to eventually merge the code bases of pim6sd and pimd.  In pimd and mrouted we have a `--disable-vifs` flag instead to change the default. I can easily port that today.

    --disable-vifs   Disable all virtual interfaces (phyint) by default

**Comment by troglobit** [comment]
Turns out this already exists (ping @T-X)!  The construct for parsing the .conf file and querying the kernel for available interfaces is different from the original pimd.  In pim6sd they added the following construct, that you add to your .conf file before all `phyint foo enable;` directives:

    default_phyint_status disable;

I'm updating the README with this hint.  It's already mentioned in the `pim6sd.conf.5` man page.

**Comment by troglobit** [comment]
@mweinelt I may have closed this a bit prematurely ... if you're not satisfied with the resolution, please let me know so I can reopen it!
